#!/system/bin/sh

# Auto set packagemanager to updateonly mode.
# You can rename this file with '-' prefix filename to disable it.
#

myname=`basename $0`
if [ "${myname:0:1}" != "-" ]; then
   if [ -f /etc/.pmReadOnly -o -f /data/.pmReadOnly -o -f /storage/sdcard0/.pmReadOnly ]; then
       #wait for boot complete
        while ! ps | grep -q mcd; do
              sleep 5
        done

        setprop ctl.stop installd
        setprop android.pm.readonly 1
   else
        setprop android.pm.readonly 0
   fi
fi
