#!/system/bin/sh

[ -f /system/etc/lockAppNet.conf ] || exit 0
setprop android.network.lockAppNet 1
setprop android.lockAppNet.ntpServerIP ""
/system/bin/lockAppNet

if [ -f /data/crontabs/lockAppNet/root ]; then 
   crond -c /data/crontabs/lockAppNet
elif [ -f /system/etc/crontabs/lockAppNet/root ]; then
   crond -c /system/etc/crontabs/lockAppNet
fi
